server:
  port: 8761

spring:
  application:
    name: EUREKA-SERVICE

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

#spring:
#  cloud:
#    config:
#      uri: http://localhost:8888